spring:
  application:
    name: diurnal-dbi-service
    heroku: ${spring.application.name}.herokuapp.com
  profiles:
    active: ${SPRING_PROFILE:local}
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME:user}
      password: ${SPRING_SECURITY_CRED:default}

server:
  port: ${SERVER_PORT:25641}

db:
  diurnal:
    name: diurnal
    server:
      host: localhost
      port: ${PROM_POSTGRES_PORT}
    user: ${PROM_POSTGRES_REF_USER}
    cred: ${PROM_POSTGRES_REF_CRED}
    url: ${LOCAL_DATABASE_URL:}

dbi:
  tables:
    create:
      onStartup: ${DBI_TABLES_CREATE_ONSTARTUP:true}
  inactive:
    timeout:
      enabled: ${DBI_INACTIVE_TIMEOUT_ENABLED:false}
      seconds: ${DBI_INACTIVE_TIMEOUT_SECONDS:30}
  shutdown:
    exit:
      code: ${DBI_SHUTDOWN_EXIT_CODE:0}
  trialPeriodDays: ${DBI_TRIAL_PERIOD_DAYS:30}

logging.level.org.springframework.web: ${LOGGING:INFO}