app:
  name: diurnal-dbi-service
  heroku: ${app.name}.herokuapp.com

quarkus:
  http:
    port: ${SERVER_PORT:25641}
  datasource:
    db-kind: postgresql
    username: hibernate
    password: hibernate
    jdbc:
      url: jdbc:postgresql://localhost:5432/hibernate_db
  security:
    users:
      embedded:
        enabled: true
        plain-text: true
        roles:
          itachi: user
        users:
          itachi: ${INTERACTION_USER_CRED}
    swagger-ui:
      path: /swagger-ui
      # always-include: true # disabled for prod
  log:
    level: ${LOGGING:INFO}

dbi:
  inactive:
    timeout:
      enabled: ${DBI_INACTIVE_TIMEOUT_ENABLED:false}
      seconds: ${DBI_INACTIVE_TIMEOUT_SECONDS:30}
  shutdown:
    exit:
      code: ${DBI_SHUTDOWN_EXIT_CODE:0}
  limit:
    period-days:
      cloud: ${DBI_LIMIT_PERIOD_DAYS_CLOUD:365}
      trialPremium: ${DBI_TRIAL_PERIOD_DAYS:30}
      cloudExemptionEmails: ${DBI_LIMIT_PERIOD_DAYS_CLOUD_EXEMPTION_EMAILS:}
  access-gh:
    baseUrl: https://api.github.com
    token: ${DBI_ACCESS_GH_TOKEN:}
    repo: ${DBI_ACCESS_GH_REPO:}
    user: ${DBI_ACCESS_GH_USER:crackcodelogn}
    commitMessage: ${DBI_ACCESS_GH_COMMIT_MSG:Took backup at %s}
    user-mapping:
      folder: backup/ump/%s
      backupFileName: ${DBI_ACCESS_GH_BACKUP_FILE_NAME_UMP:Backup-UserMapping-%s.csv}
    entry-day:
      folder: backup/edy/%s
      backupFileName: ${DBI_ACCESS_GH_BACKUP_FILE_NAME_EDY:Backup-EntryDay-%s.csv}

logging.level.org.springframework.web: ${LOGGING:INFO}