spring:
  application:
    name: diurnal-dbi-service
    heroku: ${spring.application.name}.herokuapp.com
  profiles:
    active: ${SPRING_PROFILE:local}
  security:
    user:
      name: ${SPRING_SECURITY_USERNAME:user}
      password: ${SPRING_SECURITY_CRED:default}

server:
  port: ${SERVER_PORT:25641}

dbi:
  inactive:
    timeout:
      enabled: ${DBI_INACTIVE_TIMEOUT_ENABLED:false}
      seconds: ${DBI_INACTIVE_TIMEOUT_SECONDS:30}
  shutdown:
    exit:
      code: ${DBI_SHUTDOWN_EXIT_CODE:0}
  trialPeriodDays: ${DBI_TRIAL_PERIOD_DAYS:30}

logging.level.org.springframework.web: ${LOGGING:INFO}